import Navbar from "@/components/navbar/navbar"
import { SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <header>
        <SignedOut>
          <SignInButton />
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
      </header>
      <main className="h-full">
        <Navbar />
        {children}
      </main></>
  )
}
